name: Check

on:
  # allows running workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - windows
    paths-ignore:
      - docs/**

  push:
    branches:
      - windows
    paths-ignore:
      - docs/**

jobs:
  BuildTest:
    runs-on: windows-latest
    steps:

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      # yaml-cpp package has conflicting gtest headers and is not needed for this project
      - name: Conda dependencies
        shell: bash -l {0}
        run: |
          conda install curl eigen
          conda install -c conda-forge hdf5=1.10.6
          conda remove -y yaml-cpp

      - name: Install Python Packages
        run: |
          python -m pip install wheel
          python -m pip install cython numpy pytest setuptools

      - name: Environment Variables
        shell: bash -l {0}
        run: |
          echo "HOME_PATH=$GITHUB_WORKSPACE/.." >> $GITHUB_ENV
          echo "CONDA_LOC=$(conda info --base)/Library" >> $GITHUB_ENV
          echo "PYTHON_EXECUTABLE=$(which python)" >> $GITHUB_ENV

      - name: Install MOAB
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE
          git clone https://ahnaf-tahmid@bitbucket.org/nuclear-engineering/moab.git
          cd moab
          mkdir -p build
          cd build
          cmake ../ \
                -G"Visual Studio 17 2022"  \
                -DCMAKE_INSTALL_PREFIX="${CONDA_LOC}/" \
                -DENABLE_BLASLAPACK=OFF \
                -DENABLE_FORTRAN=OFF \
                -DENABLE_NETCDF=OFF \
                -DENABLE_PYMOAB=ON \
                -DPYMOAB_INSTALL_PREFIX="${CONDA_LOC}/.." \
                -DBUILD_SHARED_LIBS=ON \
                -DPYTHON_EXECUTABLE=${PYTHON_EXECUTABLE} \
                -DENABLE_HDF5=ON \
                -DHDF5_ROOT="${CONDA_LOC}" \
                -DHDF5_hdf5_LIBRARY_RELEASE="${CONDA_LOC}/lib/libhdf5_hl.lib;${CONDA_LOC}/lib/libhdf5.lib;${CONDA_LOC}/lib/zlib.lib;${CONDA_LOC}/lib/libhdf5_cpp.lib" \
                -DCMAKE_BUILD_TYPE=Release 
          cmake --build . --config Release
          cmake --install . --config Release

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install PyDAGMC
        run: |
          python -m pip install .

      - name: Test PyDAGMC
        run: |
          python -m pip install pytest
          python -m pytest -ra tests

