name: Check

on:
  # allows running workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - windows
    paths-ignore:
      - docs/**

  push:
    branches:
      - windows
    paths-ignore:
      - docs/**

jobs:
  BuildTest:
    runs-on: windows-latest
    steps:

      - name: Install Python Packages
        run: |
          python -m pip install wheel
          python -m pip install cython numpy pytest setuptools

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      # yaml-cpp package has conflicting gtest headers and is not needed for this project
      - name: Conda dependencies
        shell: bash -l {0}
        run: |
          conda install curl eigen
          conda install -c conda-forge hdf5=1.10.6
          conda remove -y yaml-cpp

      - name: Environment Variables
        shell: bash -l {0}
        run: |
          echo "HOME_PATH=$GITHUB_WORKSPACE/.." >> $GITHUB_ENV
          echo "CONDA_LOC=$(conda info --base)/Library" >> $GITHUB_ENV

      - name: Find MOAB
        shell: bash -l {0}
        run: |
            find $CONDA_LOC -name MOAB.lib 2>/dev/null

