name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: pydagmc-ci
          auto-activate-base: false

      - name: Install MOAB
        shell: bash
        run: |
          conda install -y -c conda-forge moab=5.5.1

      - name: Install PyDAGMC
        shell: bash
        run: |
          pip install .

      - name: Test PyDAGMC
        shell: bash
        run: |
          pytest -v .

      - name: tmate debug
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3