name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          channels: conda-forge
          mamba-version: "*"
          auto-activate-base: false
          activate-environment: pydagmc-ci

      - name: Install MOAB
        shell: bash -l {0}
        run: |
          conda install -y -c conda-forge moab=5.5.1

      - name: Install PyDAGMC
        shell: bash -l {0}
        run: |
          pip install .[test]

      - name: Test PyDAGMC
        shell: bash -l {0}
        run: |
          pytest -v .

      - name: tmate debug
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3