name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Apt dependencies
        shell: bash
        run: |
          sudo apt -y update
          sudo apt install -y libgcc-9-dev \
                              libstdc++-9-dev \
                              libembree-dev \
                              python3-dev \
                              libhdf5-dev \
                              libeigen3-dev \
                              cmake

      - name: Python dependencies
        shell: bash
        run: |
          pip3 install numpy \
                      cython==0.29.37 \
                      scipy \
                      matplotlib \
                      h5py \
                      pytest

      - name: Build MOAB
        shell: bash
        run: |
          cd ~
          git clone https://bitbucket.org/fathomteam/moab.git
          cd moab
          git checkout 5.5.1
          mkdir build
          cd build
          cmake -DENABLE_HDF5=ON -DENABLE_BLASLAPACK=OFF -DENABLE_PYMOAB=ON -DCMAKE_INSTALL_PREFIX=$HOME/opt -DCMAKE_BUILD_TYPE=Release ..
          make -j4
          make install
          cd pymoab
          pip3 install .

      - name: Install
        shell: bash
        run: |
          pip install .[test,ci]

      - name: Test w/ coverage
        shell: bash
        run: |
          pytest . -v --cov=src/pydagmc --cov-branch --cov-report=xml --cov-report=term-missing

      - name: Upload coverage
        uses: codecov/codecov-action@v2
        with:
          file: coverage.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
          name: codecov-umbrella

      - name: tmate debug
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3