name: Windows Build/Test

on:
  # allows running workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - windows
    paths-ignore:
      - docs/**

  push:
    branches:
      - windows
    paths-ignore:
      - docs/**

jobs:
  BuildTest:
    runs-on: windows-latest
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      # yaml-cpp package has conflicting gtest headers and is not needed for this project
      - name: Conda dependencies
        shell: bash -l {0}
        run: |
          conda install curl eigen
          conda install -c conda-forge hdf5=1.10.6
          conda remove -y yaml-cpp

      - name: Environment Variables
        shell: bash -l {0}
        run: |
          echo "HOME_PATH=$GITHUB_WORKSPACE/.." >> $GITHUB_ENV
          echo "CONDA_LOC=C:/Miniconda/Library" >> $GITHUB_ENV
          cd ${HOME_PATH}
          mkdir install_dir

      - name: Install Python Packages
        run: |
          python -m pip install wheel
          python -m pip install "cython<3" numpy pytest setuptools

      - name: Build MOAB
        shell: bash -l {0}
        run: |
          cd ${HOME_PATH}
          git clone --depth 1 https://bitbucket.org/fathomteam/moab -b 5.3.0
          mkdir moab_build
          cd moab_build
          cmake ../moab \
                -DENABLE_BLASLAPACK=OFF \
                -DENABLE_FORTRAN=OFF \
                -DENABLE_IMESH=OFF \
                -DENABLE_TESTING=OFF \
                -DENABLE_HDF5=ON \
                -DBUILD_SHARED_LIBS=ON \
                -G"Visual Studio 17 2022"  \
                -DCMAKE_INSTALL_PREFIX=../install_dir/ \
                -DHDF5_ROOT="${CONDA_LOC}" \
                -DHDF5_hdf5_LIBRARY_RELEASE="${CONDA_LOC}/lib/libhdf5_hl.lib;${CONDA_LOC}/lib/libhdf5.lib;${CONDA_LOC}/lib/zlib.lib;${CONDA_LOC}/lib/libhdf5_cpp.lib" \
                -DCMAKE_EXE_LINKER_FLAGS="/std:c++latest -DH5_BUILT_AS_DYNAMIC_LIB" \
                -DCMAKE_MODULE_LINKER_FLAGS="/std:c++latest" \
                -DCMAKE_SHARED_LINKER_FLAGS="/std:c++latest" \
                -DCMAKE_STATIC_LINKER_FLAGS="" \
                -DCMAKE_BUILD_TYPE=Release 
          cmake --build . --config Release
          cmake --install . --config Release

      - name: Install MOAB-Python
        shell: bash -l {0}
        run: |
          which python
          ${CONDA_LOC}/bin/python -m pip install git+https://github.com/Thea-Energy/moab-python.git

      - name: Install PyDAGMC
        run: |
          ${CONDA_LOC}/bin/python -m pip install .

      - name: Test PyDAGMC
        run: |
          ${CONDA_LOC}/bin/python -m pip install pytest
          ${CONDA_LOC}/bin/python -m pytest -ra tests