name: Quick Wheel test

on:
  # allows running workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - windows
    paths-ignore:
      - docs/**

  push:
    branches:
      - windows
    paths-ignore:
      - docs/**

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python Packages
        run: |
          python -m pip install wheel
          python -m pip install "cython<3" numpy pytest setuptools

      - name: Checkout PyNE
        uses: actions/checkout@v3

      - name: Install Miniconda Windows
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
        if: matrix.os == 'windows-latest'


      - name: Install HDF5 and Eigen Windows
        run: |
          conda install curl eigen
          conda install -c conda-forge hdf5 libblas liblapack
          conda remove -y yaml-cpp
          Add-Content -Path $env:GITHUB_ENV -Value "HOME_PATH=$env:GITHUB_WORKSPACE\.."
          Add-Content -Path $env:GITHUB_ENV -Value "CONDA_LOC=C:\\Miniconda\\Library"
          Add-Content -Path $env:GITHUB_ENV -Value "EIGEN3_DIR=C:\\Miniconda\\Library"
        if: matrix.os == 'windows-latest'

      - name: Install MOAB Windows
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE
          # clone and version
          git clone --depth 1 https://bitbucket.org/fathomteam/moab -b 5.5.0
          cd moab
          mkdir -p build
          cd build
          # cmake, build, and install
          cmake ../ -G "Visual Studio 17 2022" \
            -DCMAKE_INSTALL_PREFIX="$Env:CONDA_LOC" \
            -DCMAKE_EXE_LINKER_FLAGS="/std:c++latest -DH5_BUILT_AS_DYNAMIC_LIB" \
            -DCMAKE_MODULE_LINKER_FLAGS="/std:c++latest" \
            -DCMAKE_SHARED_LINKER_FLAGS="/std:c++latest" \
            -DCMAKE_STATIC_LINKER_FLAGS="" \
            -DENABLE_HDF5=ON \
            -DHDF5_ROOT="$Env:CONDA_LOC" \
            -DHDF5_hdf5_LIBRARY_RELEASE="$Env:CONDA_LOC\\lib\\libhdf5_hl.lib;$Env:CONDA_LOC\\lib\\libhdf5.lib;$Env:CONDA_LOC\\lib\\zlib.lib;$Env:CONDA_LOC\\lib\\libhdf5_cpp.lib" \
            -DBUILD_SHARED_LIBS=ON \
            -DENABLE_PYMOAB=ON \
            -DENABLE_IMESH=OFF \
            -DENABLE_TESTING=OFF \
            -DENABLE_BLASLAPACK=OFF \
            -DENABLE_FORTRAN=OFF \
            -DCMAKE_BUILD_TYPE=Release
          make
          make install
          cd $GITHUB_WORKSPACE
          rm -rf $GITHUB_WORKSPACE/moab
          Add-Content -Path $env:GITHUB_ENV -Value "MOAB_ROOT="
          echo "MOAB_ROOT=C:\Miniconda\Library" >> $GITHUB_ENV
          echo "MOAB installed"


      - name: Install PyDAGMC
        run: |
          $(conda info --base)/bin/python -m pip install .

      - name: Test PyDAGMC
        run: |
          $(conda info --base)/bin/python -m pip install pytest
          $(conda info --base)/bin/python -m pytest -ra tests
