name: Windows

on:
  # allows running workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - windows
    paths-ignore:
      - docs/**

  push:
    branches:
      - windows
    paths-ignore:
      - docs/**

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python Packages
        run: |
          python -m pip install wheel
          python -m pip install "cython<3" numpy pytest setuptools

      - name: Checkout PyNE
        uses: actions/checkout@v3

      - name: Install Miniconda Windows
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Install HDF5 and Eigen Windows
        shell: bash -l {0}
        run: |
          conda install curl eigen
          conda install -c conda-forge hdf5 libblas liblapack
          conda remove -y yaml-cpp
          echo "HOME_PATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "CONDA_LOC=/c/Miniconda/Library" >> $GITHUB_ENV
          echo "EIGEN3_DIR=/c/Miniconda/Library" >> $GITHUB_ENV

      - name: Build MOAB
        shell: bash -l {0}
        run: |
          cd ${$GITHUB_WORKSPACE}
          git clone --depth 1 https://bitbucket.org/fathomteam/moab -b 5.3.0
          mkdir moab_build
          cd moab_build
          cmake ../moab \
                -DENABLE_BLASLAPACK=OFF \
                -DENABLE_FORTRAN=OFF \
                -DENABLE_PYMOAB=ON \
                -DENABLE_IMESH=OFF \
                -DENABLE_TESTING=OFF \
                -DENABLE_HDF5=ON \
                -DBUILD_SHARED_LIBS=ON \
                -G"Visual Studio 17 2022"  \
                -DCMAKE_INSTALL_PREFIX=../install_dir/ \
                -DHDF5_ROOT="${CONDA_LOC}" \
                -DHDF5_hdf5_LIBRARY_RELEASE="${CONDA_LOC}/lib/libhdf5_hl.lib;${CONDA_LOC}/lib/libhdf5.lib;${CONDA_LOC}/lib/zlib.lib;${CONDA_LOC}/lib/libhdf5_cpp.lib" \
                -DCMAKE_EXE_LINKER_FLAGS="/std:c++latest -DH5_BUILT_AS_DYNAMIC_LIB" \
                -DCMAKE_MODULE_LINKER_FLAGS="/std:c++latest" \
                -DCMAKE_SHARED_LINKER_FLAGS="/std:c++latest" \
                -DCMAKE_STATIC_LINKER_FLAGS="" \
                -DCMAKE_BUILD_TYPE=Release \
          cmake --build . --config Release
          cmake --install . --config Release

      - name: Install MOAB Windows
        shell: bash -l {0}
        if: matrix.os == 'windows-latest-bash'
        run: |
          cd $GITHUB_WORKSPACE
          # clone and version
          git clone --depth 1 https://bitbucket.org/fathomteam/moab -b 5.4.0
          cd moab
          mkdir -p build
          cd build
          # cmake, build, and install
          cmake ../ -G "Visual Studio 17 2022" \
            -DCMAKE_INSTALL_PREFIX=$CONDA_LOC \
            -DENABLE_HDF5=ON \
            -DHDF5_ROOT=$CONDA_LOC \
            -DHDF5_hdf5_LIBRARY_RELEASE="$CONDA_LOC/lib/libhdf5_hl.lib;$CONDA_LOC/lib/libhdf5.lib;$CONDA_LOC/lib/zlib.lib;$CONDA_LOC/lib/libhdf5_cpp.lib" \
            -DBUILD_SHARED_LIBS=ON \
            -DENABLE_PYMOAB=ON \
            -DENABLE_IMESH=OFF \
            -DENABLE_TESTING=OFF \
            -DENABLE_BLASLAPACK=OFF \
            -DENABLE_FORTRAN=OFF \
            -DCMAKE_EXE_LINKER_FLAGS="--std:c++latest -DH5_BUILT_AS_DYNAMIC_LIB" \
            -DCMAKE_MODULE_LINKER_FLAGS="/std:c++latest" \
            -DCMAKE_SHARED_LINKER_FLAGS="/std:c++latest" \
            -DCMAKE_STATIC_LINKER_FLAGS="" \
            -DCMAKE_BUILD_TYPE=Release
            cmake --build . --config Release
            cmake --install .
          cd $GITHUB_WORKSPACE
          rm -rf $GITHUB_WORKSPACE/moab
          echo "MOAB_ROOT=/c/Miniconda/Library" >> $GITHUB_ENV
          echo "MOAB installed"

      - name: Install MOAB Windows
        run: |
          Set-Location $Env:GITHUB_WORKSPACE
          # clone and version
          git clone --depth 1 https://bitbucket.org/fathomteam/moab -b 5.4.0
          Set-Location moab
          New-Item -ItemType Directory -Force -Path build
          Set-Location build
          # cmake, build, and install
          cmake ../ -G "Visual Studio 17 2022" `
              -DCMAKE_INSTALL_PREFIX="$Env:CONDA_LOC" `
              -DCMAKE_EXE_LINKER_FLAGS="/std:c++latest -DH5_BUILT_AS_DYNAMIC_LIB" `
              -DCMAKE_MODULE_LINKER_FLAGS="/std:c++latest" `
              -DCMAKE_SHARED_LINKER_FLAGS="/std:c++latest" `
              -DCMAKE_STATIC_LINKER_FLAGS="" `
              -DENABLE_HDF5=ON `
              -DHDF5_ROOT="$Env:CONDA_LOC" `
              -DHDF5_hdf5_LIBRARY_RELEASE="$Env:CONDA_LOC/lib/libhdf5_hl.lib;$Env:CONDA_LOC/lib/libhdf5.lib;$Env:CONDA_LOC/lib/zlib.lib;$Env:CONDA_LOC/lib/libhdf5_cpp.lib" `
              -DBUILD_SHARED_LIBS=ON `
              -DENABLE_PYMOAB=ON `
              -DENABLE_IMESH=OFF `
              -DENABLE_TESTING=OFF `
              -DENABLE_BLASLAPACK=OFF `
              -DENABLE_FORTRAN=OFF `
              -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          cmake --install .
          Set-Location $Env:GITHUB_WORKSPACE
          Remove-Item -Force -Recurse moab
          Add-Content -Path $env:GITHUB_ENV -Value "MOAB_ROOT=C:\Miniconda\Library"
          Write-Host "MOAB installed"

      - name: Install PyDAGMC
        run: |
          $(conda info --base)/bin/python -m pip install .

      - name: Test PyDAGMC
        run: |
          $(conda info --base)/bin/python -m pip install pytest
          $(conda info --base)/bin/python -m pytest -ra tests
