name: Windows

on:
  # allows running workflows manually
  workflow_dispatch:

  pull_request:
    branches:
      - windows
    paths-ignore:
      - docs/**

  push:
    branches:
      - windows
    paths-ignore:
      - docs/**

jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python Packages
        run: |
          python -m pip install wheel
          python -m pip install "cython<3" numpy pytest setuptools

      - name: Checkout PyNE
        uses: actions/checkout@v3

      - name: Install Miniconda Windows
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""


      - name: Install HDF5 and Eigen Windows
        shell: bash -l {0}
        run: |
          conda install curl eigen
          conda install -c conda-forge hdf5 libblas liblapack
          conda remove -y yaml-cpp
          echo "HOME_PATH=$GITHUB_WORKSPACE/.." >> $GITHUB_ENV
          echo "CONDA_LOC=/c/Miniconda/Library" >> $GITHUB_ENV
          echo "EIGEN3_DIR=/c/Miniconda/Library" >> $GITHUB_ENV

      - name: Install MOAB Windows
        shell: bash -l {0}
        run: |
          cd $GITHUB_WORKSPACE
          cd \c\Miniconda\Library\lib\
          ls


      - name: Install PyDAGMC
        run: |
          $(conda info --base)/bin/python -m pip install .

      - name: Test PyDAGMC
        run: |
          $(conda info --base)/bin/python -m pip install pytest
          $(conda info --base)/bin/python -m pytest -ra tests
